### ISSUE TITLE
Create an tbf parsing crate

### ISSUE THREAD

**Issue by alexandruradovici** [UPB-CS-OpenSourceUpstream/elf2tab#1]
For now, the tbf parsing source is in the `header.rs` file. The purpose of this is to make the tbf parse its own carte, so that it can be used in other projects.

**Comment by mihai-negru** [comment]
Should the tbf parsing crate be found under the src folder or to the root folder?

**Comment by alexandruradovici** [comment]
No, it should be its own crate in the root folder.

**Comment by mihai-negru** [comment]
Hi, I accidentally closed the last pull request, by synchronizing my master branch with the upstreams master branch, and I will work on using tbf types from the tock/tock repository instead of redefining them and will make another pull request (didn't know that it will close the pull request, sorry)

**Comment by mihai-negru** [comment]
As far I could see is that in elf2tab the `new` function is called to create an empty TbfHeader and then it starts to fill it with data, I looked at the `parse_tbf_header` from tock-tbf and seems to to the same thing, however it needs to have a header slice of u8 representing the base for the TbfHeader, so I thought it would be a good start to first populate the header slice (to modify the elf2tab code in order to create the header slice) and then to send it to the `parse_tbf_header` in order to create the TbfHeader, what is your suggestion regarding this starting point? Thanks for the answer

**Comment by alexandruradovici** [comment]
I think there are two parts here:
1. the creation and modification of a TBF header - that implies using the `std` library and collections
2. the parsing of a TBF header in *readonly* mode, that only allow the interpretation of the header, not its modification

The two parts should share data structures, some of them marked as `#[no-std]`.

**Comment by alexandruradovici** [comment]
Moved issue to https://github.com/UPB-CS-OpenSourceUpstream/tbf-parser/issues/1
